language: ruby

rvm:
  - 2.6.4

services:
  - postgresql

before_install:
  - bundle install --jobs=3
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup

cache: bundler

script:
  - bundle exec rspec
