language: ruby
rvm:
  - 2.6.4
services:
  - postgresql
before_install:
  - bundle install --jobs=3
  - bundle exec rake db:setup
  - psql -c 'create database travis_ci_test;' -U postgres
cache: bundler
script:
  - bundle exec rspec
test:
  adapter: postgresql
  database: travis_test
