version: '3'
services:
  db:
    image: postgres:12.1
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    image: mk_web
    environment:
      - DB_USERNAME='postgres'
      - DB_HOST='db'
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      /bin/sh -c "
      bundle exec rm tmp/pids/server.pid;
      bundle exec rails db:setup;
      RAILS_ENV=test bundle exec rails webpacker:compile;
      bundle exec rails server -b 0.0.0.0;"

volumes:
  bundle_cache:
  postgres:
